export const SEARCH_POKEMON_START = 'SEARCH_POKEMON_START';
export const SEARCH_POKEMON_ERROR = 'SEARCH_POKEMON_ERROR';
export const SEARCH_POKEMON_COMPLETE = 'SEARCH_POKEMON_COMPLETE';

export const GET_POKEMON_START = 'GET_POKEMON_START';
export const GET_ALL_POKEMON_ERROR = 'GET_ALL_POKEMON_ERROR';
export const GET_ALL_POKEMON_COMPLETE = 'GET_ALL_POKEMON_COMPLETE';

export const GET_ALL_POKEMON_START = 'GET_ALL_POKEMON_START';
export const GET_POKEMON_ERROR = 'GET_POKEMON_ERROR';
export const GET_POKEMON_COMPLETE = 'GET_POKEMON_COMPLETE';
